BlogBundle_homepage:
    path:     /
    defaults: { _controller: "BlogBundle:Page:index" }
    requirements:
         methods:  GET

BlogBundle_about:
    path:     /about
    defaults: { _controller: "BlogBundle:Page:about" }
    requirements:
         methods:  GET
